import {
  Brain,
  ShieldAlert,
  TriangleAlert,
  CircleCheck,
  Sparkles,
} from "lucide-react";

function AIResult({ result, loading }) {
  if (loading) {
    return (
      <div className="bg-slate-800/80 backdrop-blur-xl border border-slate-700 rounded-3xl shadow-2xl p-8 h-full">
        <div className="flex items-center gap-3 mb-8">
          <div className="bg-cyan-500 p-3 rounded-xl">
            <Brain className="text-white" size={22} />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white">
              AI Analysis
            </h2>

            <p className="text-slate-400 text-sm">
              Gemini is processing sensor data...
            </p>
          </div>
        </div>

        <div className="flex flex-col items-center justify-center py-20">
          <div className="w-16 h-16 border-4 border-cyan-500 border-t-transparent rounded-full animate-spin"></div>

          <p className="text-cyan-400 mt-6 font-semibold">
            AI is analyzing the pipeline...
          </p>

          <p className="text-slate-500 text-sm mt-2">
            This usually takes 3–5 seconds.
          </p>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="bg-slate-800/30 backdrop-blur-xl border border-slate-700 rounded-3xl shadow-2xl p-8 h-full">
        <div className="flex items-center gap-3 mb-8">
          <div className="bg-cyan-500 p-3 rounded-xl">
            <Brain className="text-white" size={22} />
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white">
              AI Analysis
            </h2>

            <p className="text-slate-400 text-sm">
              Waiting for sensor data
            </p>
          </div>
        </div>

        <div className="flex flex-col items-center justify-center py-20">
          <Sparkles size={70} className="text-slate-600" />

          <p className="text-slate-400 mt-6 text-center">
            Enter the sensor values and click
            <span className="text-cyan-400 font-semibold">
              {" "}Analyze with AI
            </span>
            to generate an intelligent pipeline report.
          </p>
        </div>
      </div>
    );
  }

  const probabilityColor =
    result.leakProbability === "High"
      ? "bg-red-500/20 text-red-400 border-red-500/30"
      : result.leakProbability === "Medium"
      ? "bg-yellow-500/20 text-yellow-400 border-yellow-500/30"
      : "bg-green-500/20 text-green-400 border-green-500/30";

  return (
    <div className="bg-slate-800/80 backdrop-blur-xl border border-slate-700 rounded-3xl shadow-2xl p-8">

      <div className="flex items-center gap-3 mb-8">
        <div className="bg-cyan-500 p-3 rounded-xl">
          <Brain className="text-white" size={22} />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">
            AI Analysis Report
          </h2>

          <p className="text-slate-400 text-sm">
            Generated by Gemini AI
          </p>
        </div>
      </div>

      <div className="space-y-6">

        <div className="flex items-center justify-between">

          <div className="flex items-center gap-3">
            <ShieldAlert className="text-cyan-400" />

            <span className="text-slate-300 font-medium">
              Leak Probability
            </span>
          </div>

          <span
            className={`px-4 py-2 rounded-full border font-semibold ${probabilityColor}`}
          >
            {result.leakProbability}
          </span>

        </div>

        <div className="flex items-center justify-between">

          <div className="flex items-center gap-3">
            <TriangleAlert className="text-yellow-400" />

            <span className="text-slate-300 font-medium">
              Severity
            </span>
          </div>

          <span className="text-white font-semibold">
            {result.severity}
          </span>

        </div>

        <div className="bg-slate-900 rounded-xl p-5">
          <h3 className="text-cyan-400 font-semibold mb-3">
            Analysis
          </h3>

          <p className="text-slate-300 leading-7">
            {result.reason}
          </p>
        </div>

        <div className="bg-green-500/10 border border-green-500/20 rounded-xl p-5">

          <div className="flex items-center gap-3 mb-3">
            <CircleCheck className="text-green-400" />

            <h3 className="text-green-400 font-semibold">
              Recommendation
            </h3>
          </div>

          <p className="text-slate-300 leading-7">
            {result.recommendation}
          </p>

        </div>

      </div>

    </div>
  );
}

export default AIResult;